apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: vote-ui
  labels:
    app: vote-ui
spec:
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
        - image: quay.io/sumitbiswal/sumit-custom-httpd:latest
          name: vote-ui
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
