apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vote-ui
  labels:
    app: vote-ui
spec:
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      type: NodePort
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
          protocol: TCP
      selector:
        app: vote-ui
